# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73feed67f592925ec6637470ccbde76e8a305cf5fe8e67720516c1f3cb70f4c395825bf490865302386bc783c91ee3e4ce7e1738f588f30f41ff640a40d0c144

test:
  secret_key_base: 5728d8429cd40b116960b256820eb211b161fe8e4912205fc730e3621d15618e325da06f2b16b673577840e45e739f5748b64395dc2992f7fa4710a774aee12c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
